### ISSUE TITLE
Mais detalhes quando há erro de envio de mensagem

### ISSUE THREAD

**Issue by GMUNDI** [wppconnect-team/wppconnect-server#1020]
Quando há erro no envio de mensagem, a informação retornada no JSON nem sempre oferece um entendimento claro e a decisão por ações a partir destas informações.

Um exemplo: um cliente informou corretamente uma URL em um envio tipo imagem, que colada no navegador abre perfeitamente. Porém ao ser carregada para envio e convertida para base64 (em PHP no meu sistema), ocorre algum erro só para esta imagem.

Monitorando o log do server identifiquei que o problema é este erro na conversão, mas no JSON de resposta do envio só informa erro e que não foi possível enviar.

A sugestão é trazer mais detalhes não só para o envio de mensagens, mas para tudo o que for possível.

Este é o erro:

 error: 2022-12-16T15:02:39.445Z Empty or invalid file or base64 - Error: Empty or invalid file or base64
     at Whatsapp.<anonymous> (/root/ozap/wppconnect-server/node_modules/@wppconnect-team/wppconnect/dist/api/layers/sender.layer.js:637:37)
     at step (/root/ozap/wppconnect-server/node_modules/@wppconnect-team/wppconnect/dist/api/layers/sender.layer.js:98:23)
     at Object.next (/root/ozap/wppconnect-server/node_modules/@wppconnect-team/wppconnect/dist/api/layers/sender.layer.js:79:53)
     at fulfilled (/root/ozap/wppconnect-server/node_modules/@wppconnect-team/wppconnect/dist/api/layers/sender.layer.js:70:58)
     at runMicrotasks (<anonymous>)
     at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by icleitoncosta** [comment]
Melhoria efetuada através do f35664a3ab8489bbb06820b819a17d778e67907f
