### ISSUE TITLE
The message error is return serialized like array on add-product-image route

### ISSUE THREAD

**Issue by IgorDePaula** [wppconnect-team/wppconnect-server#1075]
## Description

On try add product image, the message error is return serialized like array. The image can be wrong, but not the message error.

## Environment

- **Wppconnect-server version(s):** 1.8.2
- **Browser:** not informed in console
- **OS:** ubuntu 22.04
- **Node version:** 16.19
- **WhatsApp version:**2.2234.13
- **MultiDevice (BETA):** no
- **config.json:** 
```json{
  "secretKey": "THISISMYSECURETOKEN",
  "host": "http://localhost",
  "port": "21465",
  "deviceName": "WppConnect",
  "poweredBy": "WPPConnect-Server",
  "startAllSession": true,
  "tokenStoreType": "file",
  "maxListeners": 15,
  "customUserDataDir": "./userDataDir/",
  "webhook": {
    "url": null,
    "autoDownload": true,
    "uploadS3": false,
    "readMessage": true,
    "allUnreadOnStart": false,
    "listenAcks": true,
    "onPresenceChanged": true,
    "onParticipantsChanged": true,
    "onReactionMessage": true,
    "onPollResponse": true,
    "onRevokedMessage": true
  },
  "archive": {
    "enable": false,
    "waitTime": 10,
    "daysToArchive": 45
  },
  "log": {
    "level": "error",
    "logger": ["console", "file"]
  },
  "createOptions": {
    "browserArgs": [
      "--disable-web-security",
      "--no-sandbox",
      "--disable-web-security",
      "--aggressive-cache-discard",
      "--disable-cache",
      "--disable-application-cache",
      "--disable-offline-load-stale-cache",
      "--disk-cache-size=0",
      "--disable-background-networking",
      "--disable-default-apps",
      "--disable-extensions",
      "--disable-sync",
      "--disable-translate",
      "--hide-scrollbars",
      "--metrics-recording-only",
      "--mute-audio",
      "--no-first-run",
      "--safebrowsing-disable-auto-update",
      "--ignore-certificate-errors",
      "--ignore-ssl-errors",
      "--ignore-certificate-errors-spki-list"
    ]
  },
  "mapper": {
    "enable": false,
    "prefix": "tagone-"
  },
  "db": {
    "mongodbDatabase": "tokens",
    "mongodbCollection": "",
    "mongodbUser": "",
    "mongodbPassword": "",
    "mongodbHost": "",
    "mongoIsRemote": true,
    "mongoURLRemote": "",
    "mongodbPort": 27017,
    "redisHost": "localhost",
    "redisPort": 6379,
    "redisPassword": "",
    "redisDb": 0,
    "redisPrefix": "docker"
  }
}
```

## Steps to Reproduce

1. send product id and iamge in base64 for route /pi/add-product-image with postman

## Log Output

```
Error: "invalid_data_url"
    at /home/igor/projetos/wppconnect-server/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:107:31
    at step (/home/igor/projetos/wppconnect-server/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:49:23)
    at Object.next (/home/igor/projetos/wppconnect-server/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:30:53)
    at fulfilled (/home/igor/projetos/wppconnect-server/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:21:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
JS Stack: Error: "invalid_data_url"
    at /home/igor/projetos/wppconnect-server/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:104:33
    at step (/home/igor/projetos/wppconnect-server/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:49:23)
    at Object.next (/home/igor/projetos/wppconnect-server/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:30:53)
    at fulfilled (/home/igor/projetos/wppconnect-server/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:21:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  '0': 'i',
  '1': 'n',
  '2': 'v',
  '3': 'a',
  '4': 'l',
  '5': 'i',
  '6': 'd',
  '7': '_',
  '8': 'd',
  '9': 'a',
  '10': 't',
  '11': 'a',
  '12': '_',
  '13': 'u',
  '14': 'r',
  '15': 'l'
}


```
![erro add image](https://user-images.githubusercontent.com/2833993/215334862-d490f68d-f91f-4d5c-b249-ec239b7e6422.png)
![postman add image](https://user-images.githubusercontent.com/2833993/215334864-2e1db78f-b32c-437b-9589-907cacf1e22d.png)

**Comment by IgorDePaula** [comment]
The same happens in remove-product-image route

**Comment by IgorDePaula** [comment]
Uma coisa que notei, ao tentar adicionar nova imagem, o zap faz uma validacao e nao permite que a mesma imagem seja adicionada mais de uma vez no mesmo produto. Entretanto o change product image continua dando problema. Ja localizei e darei uma PR.

**Comment by IgorDePaula** [comment]
Vou fechar pq o erro de serializacao como array nao ocorre mais.
