### ISSUE TITLE
Hash mismatch on change-product-image and add-product-image routes

### ISSUE THREAD

**Issue by IgorDePaula** [wppconnect-team/wppconnect-server#1076]
## Description

I got hash mismatch on upload image base64 to catalog

## Environment

- **Wppconnect-server version(s):** 1.8.2
- **OS:** ubuntu 22.04
- **Node version:** 16.19
- **WhatsApp version:** 2.2234.13
- **MultiDevice (BETA):**no
- **config.json:*
```
{
  "secretKey": "THISISMYSECURETOKEN",
  "host": "http://localhost",
  "port": "21465",
  "deviceName": "WppConnect",
  "poweredBy": "WPPConnect-Server",
  "startAllSession": true,
  "tokenStoreType": "file",
  "maxListeners": 15,
  "customUserDataDir": "./userDataDir/",
  "webhook": {
    "url": null,
    "autoDownload": true,
    "uploadS3": false,
    "readMessage": true,
    "allUnreadOnStart": false,
    "listenAcks": true,
    "onPresenceChanged": true,
    "onParticipantsChanged": true,
    "onReactionMessage": true,
    "onPollResponse": true,
    "onRevokedMessage": true
  },
  "archive": {
    "enable": false,
    "waitTime": 10,
    "daysToArchive": 45
  },
  "log": {
    "level": "error",
    "logger": ["console", "file"]
  },
  "createOptions": {
    "browserArgs": [
      "--disable-web-security",
      "--no-sandbox",
      "--disable-web-security",
      "--aggressive-cache-discard",
      "--disable-cache",
      "--disable-application-cache",
      "--disable-offline-load-stale-cache",
      "--disk-cache-size=0",
      "--disable-background-networking",
      "--disable-default-apps",
      "--disable-extensions",
      "--disable-sync",
      "--disable-translate",
      "--hide-scrollbars",
      "--metrics-recording-only",
      "--mute-audio",
      "--no-first-run",
      "--safebrowsing-disable-auto-update",
      "--ignore-certificate-errors",
      "--ignore-ssl-errors",
      "--ignore-certificate-errors-spki-list"
    ]
  },
  "mapper": {
    "enable": false,
    "prefix": "tagone-"
  },
  "db": {
    "mongodbDatabase": "tokens",
    "mongodbCollection": "",
    "mongodbUser": "",
    "mongodbPassword": "",
    "mongodbHost": "",
    "mongoIsRemote": true,
    "mongoURLRemote": "",
    "mongodbPort": 27017,
    "redisHost": "localhost",
    "redisPort": 6379,
    "redisPassword": "",
    "redisDb": 0,
    "redisPrefix": "docker"
  }
}

```

## Steps to Reproduce

1. upload an image in base64 to routes change-product-image and add-product-image

## Log Output

```
Error [MediaInvalidError]: mmsUpload: hash mismatch: 415
    at /home/igor/projetos/wppconnect-server/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:107:31
    at step (/home/igor/projetos/wppconnect-server/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:49:23)
    at Object.next (/home/igor/projetos/wppconnect-server/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:30:53)
    at fulfilled (/home/igor/projetos/wppconnect-server/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:21:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
JS Stack: HttpStatusCodeError: mmsUpload: hash mismatch: 415
    at new i (https://web.whatsapp.com/bootstrap_qr.c8a228a8ac9e7fc0fc33.js:40:209717)
    at new a (https://web.whatsapp.com/bootstrap_qr.c8a228a8ac9e7fc0fc33.js:57:8427)
    at new o (https://web.whatsapp.com/bootstrap_qr.c8a228a8ac9e7fc0fc33.js:53:119323)
    at https://web.whatsapp.com/bootstrap_qr.c8a228a8ac9e7fc0fc33.js:53:141683
    at W (https://web.whatsapp.com/bootstrap_qr.c8a228a8ac9e7fc0fc33.js:40:119522)
    at MutationObserver.x (https://web.whatsapp.com/bootstrap_qr.c8a228a8ac9e7fc0fc33.js:40:116099) {
  status: 415
}
Error [MediaInvalidError]: mmsUpload: hash mismatch: 415
    at /home/igor/projetos/wppconnect-server/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:107:31
    at step (/home/igor/projetos/wppconnect-server/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:49:23)
    at Object.next (/home/igor/projetos/wppconnect-server/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:30:53)
    at fulfilled (/home/igor/projetos/wppconnect-server/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:21:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
JS Stack: HttpStatusCodeError: mmsUpload: hash mismatch: 415
    at new i (https://web.whatsapp.com/bootstrap_qr.c8a228a8ac9e7fc0fc33.js:40:209717)
    at new a (https://web.whatsapp.com/bootstrap_qr.c8a228a8ac9e7fc0fc33.js:57:8427)
    at new o (https://web.whatsapp.com/bootstrap_qr.c8a228a8ac9e7fc0fc33.js:53:119323)
    at https://web.whatsapp.com/bootstrap_qr.c8a228a8ac9e7fc0fc33.js:53:141683
    at W (https://web.whatsapp.com/bootstrap_qr.c8a228a8ac9e7fc0fc33.js:40:119522)
    at MutationObserver.x (https://web.whatsapp.com/bootstrap_qr.c8a228a8ac9e7fc0fc33.js:40:116099) {
  status: 415
}

```

![image](https://user-images.githubusercontent.com/2833993/215339300-7ad5291e-8a3b-4136-b546-e72815127b2e.png)

**Comment by icleitoncosta** [comment]
Opa Igor, creio que esse erro esteja vindo da LIB.
Irei dar uma geral nela essa semana e te retorno nessa issue.

**Comment by IgorDePaula** [comment]
Fantastico, aguardo ansiosamente.

**Comment by icleitoncosta** [comment]
Opa Igor, fiz uns testes agora, porém, os erros não aconteceram. 
Poderia me mostrar como você está fazendo a chamada para a rota, com o body, talvez seja algo na requisição.

É importante enviar com "data:image/png;base64," antes do base64 de fato, para o sistema identificar o que é a imagem (talvez seja isso, mas mesmo assim não consegui reproduzir o erro.

Outra coisa é que a versão do whatsapp que está pegando para você é muito antiga, tenta utilizar uma versão mais recente, até porque algumas funções das comunidades não irão funcionar na versão 2.2234.13

**Comment by IgorDePaula** [comment]
'e, vc estava certo, deveria ter sido a versao do zap, add imagem ta funcionando, change image nao, mas ja localizei onde ocorre o problema e estarei enviando PR.

**Comment by IgorDePaula** [comment]
@icleitoncosta cara, cheguei no limite do meu typescript...., mas so uma pergunta, pq aqui nao tem o atributo imagem do produto...? https://github.com/wppconnect-team/wa-js/blob/main/src/catalog/functions/editProduct.ts#L46

**Comment by IgorDePaula** [comment]
Fiz uma gambeta no wa-js, nao sei se eh o correto, eu nao entendo muito de ts.
