### ISSUE TITLE
invalid url error on add product in catalog.

### ISSUE THREAD

**Issue by lucazin** [wppconnect-team/wppconnect-server#1114]
## Description

[Description of the bug, When Issue Happens]

## Environment

{
  "secretKey": "zpzpzpzpzzp123",
  "host": "http://localhost",
  "port": "21465",
  "deviceName": "WppConnect",
  "poweredBy": "WPPConnect-Server",
  "startAllSession": true,
  "tokenStoreType": "file",
  "maxListeners": 15,
  "customUserDataDir": "./userDataDir/",
  "webhook": {
    "url": null,
    "autoDownload": false,
    "uploadS3": false,
    "readMessage": false,
    "allUnreadOnStart": false,
    "listenAcks": false,
    "onPresenceChanged": false,
    "onParticipantsChanged": false,
    "onReactionMessage": false,
    "onPollResponse": false,
    "onRevokedMessage": false
  },
  "archive": {
    "enable": false,
    "waitTime": 10,
    "daysToArchive": 45
  },
  "log": {
    "level": "error",
    "logger": ["console", "file"]
  },
  "headless": true,
  "useChrome": true,
  "createOptions": {
    "browserArgs": [
      "--disable-web-security",
      "--no-sandbox",
      "--disable-web-security",
      "--aggressive-cache-discard",
      "--disable-cache",
      "--disable-application-cache",
      "--disable-offline-load-stale-cache",
      "--disk-cache-size=0",
      "--disable-background-networking",
      "--disable-default-apps",
      "--disable-extensions",
      "--disable-sync",
      "--disable-translate",
      "--hide-scrollbars",
      "--metrics-recording-only",
      "--mute-audio",
      "--no-first-run",
      "--safebrowsing-disable-auto-update",
      "--ignore-certificate-errors",
      "--ignore-ssl-errors",
      "--ignore-certificate-errors-spki-list"
    ]
  },
  "mapper": {
    "enable": false,
    "prefix": "tagone-"
  },
  "db": {
    "mongodbDatabase": "tokens",
    "mongodbCollection": "",
    "mongodbUser": "",
    "mongodbPassword": "",
    "mongodbHost": "",
    "mongoIsRemote": true,
    "mongoURLRemote": "",
    "mongodbPort": 27017,
    "redisHost": "localhost",
    "redisPort": 6379,
    "redisPassword": "",
    "redisDb": 0,
    "redisPrefix": "docker"
  }
}

## Steps to Reproduce

1 - Payload 
2 -  Executa a chamada para adicionar novo produto  api/sessionx/add-product

## Log Output

```
If relevant, paste all of your Log Output

{
  "status": "Error",
  "message": "Error on add product.",
  "error": {
    "name": "ServerStatusCodeError",
    "errors": [
      {
        "name": "url"
      }
    ],
    "status": 406,
    "statusCode": 406
  },
  "session": "55GY2Zjlri_restaurantesaojorge"

## Error

0|server  | Error [ServerStatusCodeError]: {"name":"ServerStatusCodeError","stack":"ServerStatusCodeError\n    at new i (web.whatsapp.com/app.9e31a8725d9f2a90915f.js:40:143494)\n    at new a (web.whatsapp.com/app.9e31a8725d9f2a90915f.js:50:361568)\n    at web.whatsapp.com/app.9e31a8725d9f2a90915f.js:46:124404\n    at Generator.next (<anonymous>)\n    at t (web.whatsapp.com/vendor1~app.0c8e960e5dfd7020f562.js:2:66483)\n    at s (web.whatsapp.com/vendor1~app.0c8e960e5dfd7020f562.js:2:66694)\n    at W (web.whatsapp.com/app.9e31a8725d9f2a90915f.js:5:140550)\n    at MutationObserver.B (web.whatsapp.com/app.9e31a8725d9f2a90915f.js:5:137127)","errors":[{"name":"url"}],"status":406,"statusCode":406}


```
If relevant, paste all of your challenge code in here
```

## Additional context / Screenshot

Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by lucazin** [comment]
Retirando o campo URL e retailerID do body  funcionou.
