### ISSUE TITLE
Rest Endpoint Not generating the QR Code 

### ISSUE THREAD

**Issue by SajjadAhmad-inspire-Tech** [wppconnect-team/wppconnect-server#1190]
Hi, I have deployed this code in my local machine and also tried to run it under Azure Kubernetes Service but on both sides facing the same issue as using the  POSTMAN QR code is not generating. it's showing the following response.
{
    "status": "error",
    "message": "Error retrieving QRCode",
    "error": {
        "level": "error"
    }
}

The screenshot is also added as a reference, any body can suggest this issue?

![image](https://user-images.githubusercontent.com/104127188/231758392-1dcf6b98-d9a1-41ee-ac43-744e899026cb.png)
![image](https://user-images.githubusercontent.com/104127188/231758618-7e2a7b73-d1f2-42b5-bc96-4a3c948d66c3.png)

**Comment by SajjadAhmad-inspire-Tech** [comment]
@icleitoncosta  here is log

2023-04-13 13:02:39 error: 2023-04-13T13:02:39.295Z Cannot read properties of undefined (reading 'urlcode') - TypeError: Cannot read properties of undefined (reading 'urlcode')
2023-04-13 13:02:39     at getQrCode (/usr/src/wpp-server/dist/controller/sessionController.js:339:20)
2023-04-13 13:02:39     at Layer.handle [as handle_request] (/usr/src/wpp-server/node_modules/express/lib/router/layer.js:95:5)
2023-04-13 13:02:39     at next (/usr/src/wpp-server/node_modules/express/lib/router/route.js:144:13)
2023-04-13 13:02:39     at /usr/src/wpp-server/dist/middleware/auth.js:71:9

**Comment by icleitoncosta** [comment]
Please, before, use the "start-session" route for initialization your session.

**Comment by SajjadAhmad-inspire-Tech** [comment]
@icleitoncosta i have checked route and docs there is no endpoint/route for  initialization session.
can you suggest me?

**Comment by icleitoncosta** [comment]
Yes, have one.

This route exists on Postman and on Swagger. 

But, I suggest to you use Swagger, it is more refreshed.

In your PC, open: http://localhost:21465/api-docs

- Generate Token (route)
- Put your generated token on Authorization.
- Start session (route) 
- Click on qr-code (route) to retrieve your QR code.

**Comment by SajjadAhmad-inspire-Tech** [comment]
@icleitoncosta Thanks .
