### ISSUE TITLE
Unhandled Rejection: TypeError: Cannot read properties of undefined (reading 'access_key_id')

### ISSUE THREAD

**Issue by jxngTM** [wppconnect-team/wppconnect-server#1378]
## Description

When deploying docker containers, wppconnect-server throws Unhandled Rejection: TypeError: Cannot read properties of undefined (reading 'access_key_id') and nginx shows 502 Bad Gateway

## Environment

- **Wppconnect-server version(s):** 2.2.4
- **Browser:** any/not applicable
- **OS:** VPS: Ubuntu 20.04.6 LTS aarch64
- **Node version:** Node 18.16.1 LTS/any
- **WhatsApp version:** not applicable
- **MultiDevice (BETA):** not applicable
- **config.json:** DEFAULT, NO CHANGES MADE

## Steps to Reproduce

1. clone wpp-docker repo
2. deploy the compose file located on wpp-docker/docker-server-front/docker-compose.yaml

## Log Output

```
root@aapanel:/www/wwwroot/wppconnect/wppconnect-server# docker logs wppconnect-server 
yarn run v1.22.19
$ cross-env TS_NODE_FILES=true TS_NODE_TRANSPILE_ONLY=true NODE_PATH=src nodemon --watch src --exec ts-node --esm src/server.ts -e ts
[nodemon] 3.0.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): src/**/*
[nodemon] watching extensions: ts
[nodemon] starting `ts-node --esm src/server.ts`
error:    Unhandled Rejection: TypeError: Cannot read properties of undefined (reading 'access_key_id')
    at initServer (/home/node/app/src/index.ts:60:21)
    at Object.<anonymous> (/home/node/app/src/server.ts:19:11)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module.m._compile (/home/node/app/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Object.require.extensions.<computed> [as .ts] (/home/node/app/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Function.Module._load (node:internal/modules/cjs/loader:960:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
[nodemon] clean exit - waiting for changes before restart
root@aapanel:/www/wwwroot/wppconnect/wppconnect-server#
```

## Your Code

```
NOT APPLICABLE
```

## Additional context / Screenshot

![image](https://github.com/wppconnect-team/wppconnect-server/assets/58450254/f070870a-e202-4cee-94fc-d63056df004d)
![image](https://github.com/wppconnect-team/wppconnect-server/assets/58450254/453d803f-6fcc-4548-a36e-30cf9ffbc57d)
![image](https://github.com/wppconnect-team/wppconnect-server/assets/58450254/9a402f02-d877-4b8e-9f49-7e6b1c41eafa)

**Comment by icleitoncosta** [comment]
Thanks for the issue. I will fix this

**Comment by renat473** [comment]
Hello @jxngTM 

are you using the frontend in react?

If so, this project has been discontinued.

**Comment by renat473** [comment]
you could update the config.ts file found in the wppconnect-server repository.

because what is in the wpp-docker repository is outdated.

**Comment by jxngTM** [comment]
opa, a parte do backend está ok agora

troquei o front pra vue e fui testar, e sempre acusa sessão/token incorreto, mesmo estando correto

![Screenshot_2](https://github.com/wppconnect-team/wppconnect-server/assets/58450254/aa8f952d-a7cc-44ac-a0e4-c04f5c0e5bbe)

isso aconteceu em versões anteriores também

o que pode ser?

se necessário, pode testar, o IP e o token estão na screenshot
