### ISSUE TITLE
MongoDB: Substituir ID

### ISSUE THREAD

**Issue by moskoweb** [wppconnect-team/wppconnect-server#155]
Quando tenta atualizar uma sessão, no mongodb da o seguinte erro:
```
0|npm  | UnhandledRejection: Performing an update on the path '_id' would modify the immutable field '_id'
0|npm  |     at Function.create (/root/wppconnect-server/node_modules/mongodb/lib/core/error.js:57:12)
0|npm  |     at toError (/root/wppconnect-server/node_modules/mongodb/lib/utils.js:130:22)
0|npm  |     at /root/wppconnect-server/node_modules/mongodb/lib/operations/common_functions.js:384:39
0|npm  |     at handler (/root/wppconnect-server/node_modules/mongodb/lib/core/sdam/topology.js:953:24)
0|npm  |     at /root/wppconnect-server/node_modules/mongodb/lib/cmap/connection_pool.js:350:13
0|npm  |     at handleOperationResult (/root/wppconnect-server/node_modules/mongodb/lib/core/sdam/server.js:565:5)
0|npm  |     at MessageStream.messageHandler (/root/wppconnect-server/node_modules/mongodb/lib/cmap/connection.js:281:5)
0|npm  |     at MessageStream.emit (events.js:314:20)
0|npm  |     at processIncomingData (/root/wppconnect-server/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
0|npm  |     at MessageStream._write (/root/wppconnect-server/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
0|npm  |     at doWrite (_stream_writable.js:403:12)
0|npm  |     at writeOrBuffer (_stream_writable.js:387:5)
0|npm  |     at MessageStream.Writable.write (_stream_writable.js:318:11)
0|npm  |     at TLSSocket.ondata (_stream_readable.js:718:22)
0|npm  |     at TLSSocket.emit (events.js:314:20)
0|npm  |     at addChunk (_stream_readable.js:297:12)
0|npm  |     at readableAddChunk (_stream_readable.js:272:9)
0|npm  |     at TLSSocket.Readable.push (_stream_readable.js:213:10)
0|npm  |     at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23)
```

E depois ele derruba o servidor.

**Comment by hbdbim** [comment]
Qual endpoint do server esta sendo chamado, quais os dados passados no request ?

**Comment by moskoweb** [comment]
Isso ocorre quando tenta reconectar uma sessão que foi desconectada.
