### ISSUE TITLE
puppeteer Error on logout api:  Requesting main frame too early!

### ISSUE THREAD

**Issue by mitnick2012** [wppconnect-team/wppconnect-server#1647]
## Environment

- **Wppconnect-server version(s):**2.3.0
- **Browser:** [e.g. Chrome 87, Chromium 85]
- **OS:** Ubuntu
- **Node version:**  Node 20

## Steps to Reproduce

1. call  generate  token
2. get qr code 
3. and logout api 

## Log Output

```
Error: Requesting main frame too early!
    at assert (/home/whatsuser/Desktop/WhatsAppApi-2.3.0/node_modules/puppeteer-core/lib/cjs/puppeteer/util/assert.js:28:15)
    at FrameManager.mainFrame (/home/whatsuser/Desktop/WhatsAppApi-2.3.0/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/FrameManager.js:223:32)
    at CdpPage.mainFrame (/home/whatsuser/Desktop/WhatsAppApi-2.3.0/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Page.js:415:35)
    at CdpPage.addScriptTag (/home/whatsuser/Desktop/WhatsAppApi-2.3.0/node_modules/puppeteer-core/lib/cjs/puppeteer/api/Page.js:510:31)
    at /home/whatsuser/Desktop/WhatsAppApi-2.3.0/node_modules/@wppconnect-team/wppconnect/dist/controllers/browser.js:307:47
    at step (/home/whatsuser/Desktop/WhatsAppApi-2.3.0/node_modules/@wppconnect-team/wppconnect/dist/controllers/browser.js:83:23)
    at Object.next (/home/whatsuser/Desktop/WhatsAppApi-2.3.0/node_modules/@wppconnect-team/wppconnect/dist/controllers/browser.js:64:53)
    at fulfilled (/home/whatsuser/Desktop/WhatsAppApi-2.3.0/node_modules/@wppconnect-team/wppconnect/dist/controllers/browser.js:55:58)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at process.processTimers (node:internal/timers:509:9)
verbose:  [Session1:client] wapi.js failed

```

**Comment by icleitoncosta** [comment]
Please, update your project
