### ISSUE TITLE
Double @c.us

### ISSUE THREAD

**Issue by antirek** [wppconnect-team/wppconnect-server#17]
I start wppconnect-server and connect wppconnect-client to wppconnect-server successfully. 
I login to UI and receive error in server console

invalid wid

`````
info: 2021-05-14T15:58:40.037Z Started Session: mySession
info: 2021-05-14T15:58:40.038Z mySession : Inicio enviar mensagens n�o lidas
info: 2021-05-14T15:58:40.038Z mySession : Inicio arquivando chats
info: 2021-05-14T15:58:40.253Z mySession : Fim enviar mensagens n�o lidas
info: 2021-05-14T15:58:40.553Z ID: icNSSuqUNWQafdgOAAAB saiu
info: 2021-05-14T15:58:41.149Z ID: wmRjtzppFZzY-SytAAAD entrou
[]
info: 2021-05-14T15:58:46.565Z mySession : Fim arquivando chats
error: 2021-05-14T15:59:15.166Z Evaluation failed: Error: wid error: invalid wid: 74992907555@c.us@c.us
    at new c (https://web.whatsapp.com/bootstrap_qr.21cdeb5afaacd0e5706a.js:1:1098920)
    at new s (https://web.whatsapp.com/bootstrap_qr.21cdeb5afaacd0e5706a.js:1:1103210)
    at Object.window.WAPI.window.WAPI.checkNumberStatus (/home/sergey/Projects/wppconnect-server/node_modules/@wppconnect-team/wppconnect/dist/lib/wapi/wapi.js:1:64659)
    at async Object.window.WAPI.window.WAPI.sendExist (/home/sergey/Projects/wppconnect-server/node_modules/@wppconnect-team/wppconnect/dist/lib/wapi/wapi.js:1:31695)
    at async Object.window.WAPI.window.WAPI.getAllMessagesInChat (/home/sergey/Projects/wppconnect-server/node_modules/@wppconnect-team/wppconnect/dist/lib/wapi/wapi.js:1:56557) - Error: Evaluation failed: Error: wid error: invalid wid: 74992907555@c.us@c.us
    at new c (https://web.whatsapp.com/bootstrap_qr.21cdeb5afaacd0e5706a.js:1:1098920)
    at new s (https://web.whatsapp.com/bootstrap_qr.21cdeb5afaacd0e5706a.js:1:1103210)
    at Object.window.WAPI.window.WAPI.checkNumberStatus (/home/sergey/Projects/wppconnect-server/node_modules/@wppconnect-team/wppconnect/dist/lib/wapi/wapi.js:1:64659)
    at async Object.window.WAPI.window.WAPI.sendExist (/home/sergey/Projects/wppconnect-server/node_modules/@wppconnect-team/wppconnect/dist/lib/wapi/wapi.js:1:31695)
    at async Object.window.WAPI.window.WAPI.getAllMessagesInChat (/home/sergey/Projects/wppconnect-server/node_modules/@wppconnect-team/wppconnect/dist/lib/wapi/wapi.js:1:56557)
    at ExecutionContext._evaluateInternal (/home/sergey/Projects/wppconnect-server/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:217:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async ExecutionContext.evaluate (/home/sergey/Projects/wppconnect-server/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:106:16)
`````

**Comment by hbdbim** [comment]
the front will be fixed soon

**Comment by rodriguesabner** [comment]
Fixed
