### ISSUE TITLE
Error on building

### ISSUE THREAD

**Issue by hafiziruslan** [wppconnect-team/wppconnect-server#1797]
## Description

error on building source code

## Environment

- **Wppconnect-server version(s):** n/a
- **Browser:** n/a
- **OS:** Win10
- **Node version:** Node 20.12.1 (LTS)
- **WhatsApp version:** n/a
- **MultiDevice (BETA):** n/a
- **config.json:** n/a

## Log Output

```
yarn build
``` 
```
> @wppconnect/server@2.4.2 build:types
> tsc

src/util/tokenStore/FileTokenStore/FileTokenStore.ts:20:22 - error TS2307: Cannot find module 'sanitize-filename' or its corresponding type declarations.

20 import sanitize from 'sanitize-filename';

Found 1 error in src/util/tokenStore/FileTokenStore/FileTokenStore.ts:20
```

## Additional context / Screenshot

building success after adding 'sanitize-filename' into the dependency.

```
yarn add sanitize-filename
```

it throw this error on start
```
~\.pnp.cjs:24933
      Error.captureStackTrace(firstError);

Error: Your application tried to access @babel/runtime, but it isn't declared in your dependencies; this makes the require call ambiguous and unsound.

Required package: @babel/runtime (via "@babel\runtime\helpers\interopRequireDefault")
Required by: ~\dist\

Require stack:
- ~\dist\server.js
    at require$$0.Module._resolveFilename (~\.pnp.cjs:24933:13)
    at Module._load (node:internal/modules/cjs/loader:984:27)
    at require$$0.Module._load (~\.pnp.cjs:24824:31)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (~\dist\server.js:1:43)
    at Module._compile (node:internal/modules/cjs/loader:1369:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
    at require$$0.Module._extensions..js (~\.pnp.cjs:24976:33)
    at Module.load (node:internal/modules/cjs/loader:1206:32)

Node.js v20.12.1
```
and this
```
~\.pnp.cjs:24935
      Error.captureStackTrace(firstError);

Error: Your application tried to access mime-types, but it isn't declared in your dependencies; this makes the require call ambiguous and unsound.

Required package: mime-types
Required by: ~\dist\util\

Require stack:
- ~\dist\util\functions.js
- ~\dist\controller\catalogController.js
- ~\dist\routes\index.js
- ~\dist\index.js
- ~\dist\server.js
    at require$$0.Module._resolveFilename (~\.pnp.cjs:24935:13)
    at Module._load (node:internal/modules/cjs/loader:984:27)
    at require$$0.Module._load (~\.pnp.cjs:24826:31)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (~\dist\util\functions.js:26:41)
    at Module._compile (node:internal/modules/cjs/loader:1369:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
    at require$$0.Module._extensions..js (~\.pnp.cjs:24978:33)
    at Module.load (node:internal/modules/cjs/loader:1206:32)
    at Module._load (node:internal/modules/cjs/loader:1022:12)
    at require$$0.Module._load (~\.pnp.cjs:24826:31)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (~\dist\controller\catalogController.js:18:18)
    at Module._compile (node:internal/modules/cjs/loader:1369:14)

Node.js v20.12.1
```

start success after adding those dependencies.

```
yarn add @babel/runtime mime-types
```

**Comment by adarshmadrecha** [comment]
@hafiziruslan Thanks for listing down the requirements.
Apart from what you mentioned, I had to also run
```bash
yarn add puppeteer-extra-plugin-user-preferences
yarn add puppeteer-extra-plugin-stealth
yarn add puppeteer-extra-plugin-user-data-dir
```
