### ISSUE TITLE
Getting WAPI is not Defined

### ISSUE THREAD

**Issue by manish-snappe** [wppconnect-team/wppconnect-server#1854]
Getting this issue. Any idea ? 

debug:    [mySession7:client] Registering onPresenceChanged event
error: 2024-05-15T03:51:35.932Z WAPI is not defined - Error: WAPI is not defined
    at /home/ubuntu/node_modules/@wppconnect/server/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:107:31
    at step (/home/ubuntu/node_modules/@wppconnect/server/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:49:23)
    at Object.next (/home/ubuntu/node_modules/@wppconnect/server/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:30:53)
    at fulfilled (/home/ubuntu/node_modules/@wppconnect/server/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:21:58)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at process.processImmediate (node:internal/timers:447:9)
JS Stack: ReferenceError: WAPI is not defined
    at pptr:evaluate;%2Fhome%2Fubuntu%2Fnode_modules%2F%40wppconnect%2Fserver%2Fnode_modules%2F%40wppconnect-team%2Fwppconnect%2Fdist%2Fapi%2Fhelpers%2Fevaluate-and-return.js%3A99%3A56:56:47
    at pptr:evaluate;%2Fhome%2Fubuntu%2Fnode_modules%2F%40wppconnect%2Fserver%2Fnode_modules%2F%40wppconnect-team%2Fwppconnect%2Fdist%2Fapi%2Fhelpers%2Fevaluate-and-return.js%3A99%3A56:56:77
    at new Promise (<anonymous>)
    at anonymous (pptr:evaluate;%2Fhome%2Fubuntu%2Fnode_modules%2F%40wppconnect%2Fserver%2Fnode_modules%2F%40wppconnect-team%2Fwppconnect%2Fdist%2Fapi%2Fhelpers%2Fevaluate-and-return.js%3A99%3A56:54:14)
Function: function () { return WAPI.isConnected(); }
info:     [mySession7:session] Session Unpaired
verbose:  [mySession7:client] wapi.js injected
info: 2024-05-15T03:51:38.683Z desconnectedMobile

debug:    [mySession7:client] Exposing onAnyMessage function
verbose:  [mySession7:page] Page Closed
info: 2024-05-15T03:51:39.212Z browserClose

**Comment by gitdedc** [comment]
Did you check the lib version and whatsapp version?
If yes, delete session folder into userDataDir and restart API.

**Comment by gitdedc** [comment]
I found the problem.. investigating the solution

**Comment by gitdedc** [comment]
Using issue #1863
