### ISSUE TITLE
 WAPI is not defined

### ISSUE THREAD

**Issue by sharmasaurabh7887** [wppconnect-team/wppconnect-server#1855]
## Description

After Scan qr code from device got an error 

error: 2024-05-15T13:47:20.564Z WAPI is not defined - Error: WAPI is not defined
    at /home/ubuntu/wppconnect-server/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:107:31
    at step (/home/ubuntu/wppconnect-server/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:49:23)
    at Object.next (/home/ubuntu/wppconnect-server/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:30:53)
    at fulfilled (/home/ubuntu/wppconnect-server/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:21:58)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at process.processImmediate (node:internal/timers:449:9)
JS Stack: ReferenceError: WAPI is not defined
    at pptr:evaluate;%2Fhome%2Fubuntu%2Fwppconnect-server%2Fnode_modules%2F%40wppconnect-team%2Fwppconnect%2Fdist%2Fapi%2Fhelpers%2Fevaluate-and-return.js%3A99%3A56:56:47
    at pptr:evaluate;%2Fhome%2Fubuntu%2Fwppconnect-server%2Fnode_modules%2F%40wppconnect-team%2Fwppconnect%2Fdist%2Fapi%2Fhelpers%2Fevaluate-and-return.js%3A99%3A56:56:77
    at new Promise (<anonymous>)
    at anonymous (pptr:evaluate;%2Fhome%2Fubuntu%2Fwppconnect-server%2Fnode_modules%2F%40wppconnect-team%2Fwppconnect%2Fdist%2Fapi%2Fhelpers%2Fevaluate-and-return.js%3A99%3A56:54:14)
Function: function () { return WAPI.isConnected(); }

**Comment by sidd82** [comment]
im facing same issue

**Comment by akk-akk** [comment]
Hi, I'm also experiencing the same connectivity issues with WhatsApp  **on server deployment**. 
But when connecting to a local host, it works perfectly as expected.

**Comment by akk-akk** [comment]
> Did you check the lib version and whatsapp version? If yes, delete session folder into userDataDir and restart API.

Can you please confirm, how to check these?

**Comment by gitdedc** [comment]
I found the problem.. investigating the solution

**Comment by gitdedc** [comment]
Using issue #1863
