### ISSUE TITLE
WAPI is not defined

### ISSUE THREAD

**Issue by sidd82** [wppconnect-team/wppconnect-server#1856]
error: 2024-05-16T09:11:51.090Z WAPI is not defined - Error: WAPI is not defined
    at /root/wppconnect-server/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:107:31
    at step (/root/wppconnect-server/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:49:23)
    at Object.next (/root/wppconnect-server/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:30:53)
    at fulfilled (/root/wppconnect-server/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:21:58)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at process.processImmediate (node:internal/timers:449:9)
JS Stack: ReferenceError: WAPI is not defined
    at pptr:evaluate;%2Froot%2Fwppconnect-server%2Fnode_modules%2F%40wppconnect-team%2Fwppconnect%2Fdist%2Fapi%2Fhelpers%2Fevaluate-and-return.js%3A99%3A56:56:47
    at pptr:evaluate;%2Froot%2Fwppconnect-server%2Fnode_modules%2F%40wppconnect-team%2Fwppconnect%2Fdist%2Fapi%2Fhelpers%2Fevaluate-and-return.js%3A99%3A56:56:77
    at new Promise (<anonymous>)
    at anonymous (pptr:evaluate;%2Froot%2Fwppconnect-server%2Fnode_modules%2F%40wppconnect-team%2Fwppconnect%2Fdist%2Fapi%2Fhelpers%2Fevaluate-and-return.js%3A99%3A56:54:14)
Function: function () { return WAPI.isConnected(); }
debug:    [NERDWHATS_AMERICA:client] Registering onStateChange event
debug:    [NERDWHATS_AMERICA:client] Registering onMessage event
debug:    [NERDWHATS_AMERICA:client] Registering onAnyMessage event
debug:    [NERDWHATS_AMERICA:client] Registering onIncomingCall event
debug:    [NERDWHATS_AMERICA:client] Registering onAck event
debug:    [NERDWHATS_AMERICA:client] Registering onPresenceChanged event

**Comment by gitdedc** [comment]
I found the problem.. investigating the solution

**Comment by gitdedc** [comment]
Using issue #1863
