### ISSUE TITLE
Erro em Propriedade 'filter'

### ISSUE THREAD

**Issue by moskoweb** [wppconnect-team/wppconnect-server#207]
```
error: 2021-08-27T15:51:38.192Z Cannot read property 'filter' of undefined - TypeError: Cannot read property 'filter' of undefined
    at archive (/root/wppconnect-server/dist/util/functions.js:174:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async startHelper (/root/wppconnect-server/dist/util/functions.js:143:41)
```

**Comment by ghsgabriel** [comment]
@moskoweb , isso ainda acontece na ultima versão do server? 

Como eu poderia reproduzir esse erro?
