### ISSUE TITLE
Erro para ler mensagem não lidas ao iniciar

### ISSUE THREAD

**Issue by moskoweb** [wppconnect-team/wppconnect-server#27]
Erro quando vai reinicializar e precisa carregar as mensagens não lidas.
```
error: 2021-06-02T15:29:26.769Z Cannot read property 'length' of undefined - TypeError: Cannot read property 'length' of undefined
    at _callee5$ (/root/wppconnect-server/dist/util/functions.js:195:63)
    at tryCatch (/root/wppconnect-server/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/root/wppconnect-server/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.<computed> [as next] (/root/wppconnect-server/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/root/wppconnect-server/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /root/wppconnect-server/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by rodriguesabner** [comment]
FIXED https://github.com/wppconnect-team/wppconnect-server/commit/2f2fbb65dd761d9f8eb74e485a5b0d3f67eb8374
