### ISSUE TITLE
Erro ao criar um grupo

### ISSUE THREAD

**Issue by ObianSistemas** [wppconnect-team/wppconnect-server#32]
Por favor poderia verificar se tem algum problema ao criar um grupo, aqui usando o endpoint create-group

curl -X 'POST' \
  'http://obian.com.br:3333/api/Obian/create-group' \
  -H 'accept: */*' \
  -H 'Authorization: Bearer $2b$10$NIQ_Qw7oYDoppBT1.OSD_e_WLOyfmrwFEM.nrL5ZdHERuyHJxIgD2' \
  -H 'Content-Type: application/json' \
  -d '{
  "name": "This is My Group",
  "participants": ["554884288998","554899797488"]
}'

A resposta é que teve um **erro ao criar o grupo**

no server a info dos erros são:
error: 2021-06-09T11:08:27.167Z Evaluation failed: TypeError: window.Store.WapQuery.createGroup is not a function
    at Object.window.WAPI.window.WAPI.createGroup (/home/ubuntu/wppconnect/wppconnect-server/node_modules/@wppconnect-team/wppconnect/dist/lib/wapi/wapi.js:1:35707) - Error: Evaluation failed: TypeError: window.Store.WapQuery.createGroup is not a function
    at Object.window.WAPI.window.WAPI.createGroup (/home/ubuntu/wppconnect/wppconnect-server/node_modules/@wppconnect-team/wppconnect/dist/lib/wapi/wapi.js:1:35707)
    at ExecutionContext._evaluateInternal (/home/ubuntu/wppconnect/wppconnect-server/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:217:19)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at ExecutionContext.evaluate (/home/ubuntu/wppconnect/wppconnect-server/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:106:16)

**Comment by hbdbim** [comment]
Verificado, server atualizado, metodo funcionando
