### ISSUE TITLE
erro ao fechar sessao direto no celular e tambem no metodo logout

### ISSUE THREAD

**Issue by tomsilva** [wppconnect-team/wppconnect-server#36]
**cuando fehco a sessao direto no celular me sai essa mensagem**

error:    [teste:page] Page Closed
info: 2021-06-12T20:46:37.329Z browserClose

warn:     [teste:client] Failed to authenticate
info: 2021-06-12T20:46:37.573Z qrReadError

error:    [teste:client] Unknow error

**logo depois quando vou tentar reconectar o celullar sai esse erro**

error: 2021-06-12T20:52:24.516Z Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed. - Error: Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed.
    at CDPSession.send (D:\wppserver2\wppconnect-server\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:195:35)
    at ExecutionContext._evaluateInternal (D:\wppserver2\wppconnect-server\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:200:50)
    at ExecutionContext.evaluate (D:\wppserver2\wppconnect-server\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:106:27)
    at DOMWorld.evaluate (D:\wppserver2\wppconnect-server\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:90:24)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
info: 2021-06-12T20:54:17.613Z State Change OPENING: teste
info: 2021-06-12T20:54:17.614Z State Change OPENING: teste
info: 2021-06-12T20:54:17.773Z State Change PAIRING: teste
info: 2021-06-12T20:54:17.775Z State Change PAIRING: teste
info: 2021-06-12T20:54:20.166Z State Change CONNECTED: teste
info: 2021-06-12T20:54:20.167Z State Change CONNECTED: teste
warn:     [teste:token] Failed to update session token

**e esse e um fatal error por que ja nao consigo abrir a sessao novamente so reiniaindo o server**

**Comment by tiagodurante** [comment]
same problem

**Comment by engenheirodiegocosta** [comment]
same too.

**Comment by fabioselau077** [comment]
same
