### ISSUE TITLE
Error Versão Mais recente WppConnect-server V1.1.10 + Chatwoot (DOCKER)

### ISSUE THREAD

**Issue by willph** [wppconnect-team/wppconnect-server#361]
Caixa de entrada parou de enviar mensagem na versão mais recente.

Recebimento de mensagem OK

Erro apresentado.

```
nfo: 2021-11-13T12:56:13.389Z Started Session: will-server

TypeError: Cannot read property 'createWid' of undefined

    at Object.<anonymous> (/home/node/app/node_modules/@wppconnect-team/wppconnect/dist/lib/wapi/wapi.js:1:110360)

    at Generator.next (<anonymous>)

    at vo (/home/node/app/node_modules/@wppconnect-team/wppconnect/dist/lib/wapi/wapi.js:1:85350)

    at a (/home/node/app/node_modules/@wppconnect-team/wppconnect/dist/lib/wapi/wapi.js:1:85554)

    at /home/node/app/node_modules/@wppconnect-team/wppconnect/dist/lib/wapi/wapi.js:1:85615

    at j (https://web.whatsapp.com/bootstrap_qr.6a499aa48d60caaefb11.js:2:390225)

    at new g (https://web.whatsapp.com/bootstrap_qr.6a499aa48d60caaefb11.js:2:381120)

    at Object.<anonymous> (/home/node/app/node_modules/@wppconnect-team/wppconnect/dist/lib/wapi/wapi.js:1:85494)

    at Object.checkNumberStatus (/home/node/app/node_modules/@wppconnect-team/wppconnect/dist/lib/wapi/wapi.js:1:110591)

    at Object.<anonymous> (/home/node/app/node_modules/@wppconnect-team/wppconnect/dist/lib/wapi/wapi.js:1:64484)
```

**Comment by ghsgabriel** [comment]
Oi @willph  , esse erro continua acontecendo na ultima versão do server? Se sim, como eu posso reproduzir o erro?
