### ISSUE TITLE
Cannot read property 'numberExists' of undefined - TypeError: Cannot read property 'numberExists' of undefined     at statusConnection (/root/whatsapp/wppconnect-server-main/src/middleware/statusConnection.js:32:24)

### ISSUE THREAD

**Issue by danmarris12** [wppconnect-team/wppconnect-server#365]
info: 2021-11-14T00:38:32.795Z sohiljainwhatsapp : Inicio arquivando chats
TypeError: Cannot read properties of undefined (reading 'createWid')
    at Object.<anonymous> (/root/whatsapp/wppconnect-server-main/node_modules/@wppconnect-team/wppconnect/dist/lib/wapi/wapi.js:1:110360)
    at Generator.next (<anonymous>)
    at vo (/root/whatsapp/wppconnect-server-main/node_modules/@wppconnect-team/wppconnect/dist/lib/wapi/wapi.js:1:85350)
    at a (/root/whatsapp/wppconnect-server-main/node_modules/@wppconnect-team/wppconnect/dist/lib/wapi/wapi.js:1:85554)
    at /root/whatsapp/wppconnect-server-main/node_modules/@wppconnect-team/wppconnect/dist/lib/wapi/wapi.js:1:85615
    at j (https://web.whatsapp.com/bootstrap_qr.37b05cd2420f8e06848b.js:2:390225)
    at new g (https://web.whatsapp.com/bootstrap_qr.37b05cd2420f8e06848b.js:2:381120)
    at Object.<anonymous> (/root/whatsapp/wppconnect-server-main/node_modules/@wppconnect-team/wppconnect/dist/lib/wapi/wapi.js:1:85494)
    at Object.checkNumberStatus (/root/whatsapp/wppconnect-server-main/node_modules/@wppconnect-team/wppconnect/dist/lib/wapi/wapi.js:1:110591)
    at __puppeteer_evaluation_script__:44:68
error: 2021-11-14T00:38:42.404Z Cannot read property 'numberExists' of undefined - TypeError: Cannot read property 'numberExists' of undefined
    at statusConnection (/root/whatsapp/wppconnect-server-main/src/middleware/statusConnection.js:32:24)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
TypeError: Cannot read properties of undefined (reading 'createWid')
    at Object.<anonymous> (/root/whatsapp/wppconnect-server-main/node_modules/@wppconnect-team/wppconnect/dist/lib/wapi/wapi.js:1:110360)
    at Generator.next (<anonymous>)
    at vo (/root/whatsapp/wppconnect-server-main/node_modules/@wppconnect-team/wppconnect/dist/lib/wapi/wapi.js:1:85350)
    at a (/root/whatsapp/wppconnect-server-main/node_modules/@wppconnect-team/wppconnect/dist/lib/wapi/wapi.js:1:85554)
    at /root/whatsapp/wppconnect-server-main/node_modules/@wppconnect-team/wppconnect/dist/lib/wapi/wapi.js:1:85615
    at j (https://web.whatsapp.com/bootstrap_qr.37b05cd2420f8e06848b.js:2:390225)
    at new g (https://web.whatsapp.com/bootstrap_qr.37b05cd2420f8e06848b.js:2:381120)
    at Object.<anonymous> (/root/whatsapp/wppconnect-server-main/node_modules/@wppconnect-team/wppconnect/dist/lib/wapi/wapi.js:1:85494)
    at Object.checkNumberStatus (/root/whatsapp/wppconnect-server-main/node_modules/@wppconnect-team/wppconnect/dist/lib/wapi/wapi.js:1:110591)
    at __puppeteer_evaluation_script__:44:68
error: 2021-11-14T00:38:43.934Z Cannot read property 'numberExists' of undefined - TypeError: Cannot read property 'numberExists' of undefined
    at statusConnection (/root/whatsapp/wppconnect-server-main/src/middleware/statusConnection.js:32:24)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
TypeError: Cannot read properties of undefined (reading 'createWid')
    at Object.<anonymous> (/root/whatsapp/wppconnect-server-main/node_modules/@wppconnect-team/wppconnect/dist/lib/wapi/wapi.js:1:110360)
    at Generator.next (<anonymous>)

**Comment by edgardmessias** [comment]
@danmarris12 , try to update the `@wppconnect-team/wppconnect` to 1.10.2
