### ISSUE TITLE
Sequência do problema que observei onde o Servidor deu "crashed"

### ISSUE THREAD

**Issue by OcidentalInfo** [wppconnect-team/wppconnect-server#470]
- Minha aplicação inicia com "generate-token";
- Em seguida, é chamado "start-session";
- Com status "QRCODE" faço a leitura pelo meu Celular;
- O "status-session" passa a apresentar o status "CONNECTED";
- Começo a operar normalmente, inclusive enviando mensagens...
- Daí, resolvo "Desconectar", manualmente, meu Celular nas configurações do meu WhatsApp para "Testar esta situação";
- Com alguns segundos depois, o "check-connection-session" aponta que não está mais conectado;
- Em seguida, rodo o "start-session", novamente, sendo que, o QRCode vem "null";
- Obtenho o QRCode chamando o "status-session" e faço a leitura, novamente, do mesmo Celular e o WhatsApp conecta normalmente;
- A PARTIR DAÍ, começa o problema...
- Pois, o "status-session" não apresenta mais "CONNECTED", fica sempre com status "QRCODE";
- Se chamo "send-message", ele dá um erro no "catch" com o status: "Disconnected";
- Daí, se chamo "start-session", novamente, e ele apresenta no Terminal do Servidor o ERRO:

info: 2022-01-16T18:21:13.631Z State Change CONFLICT: informs
info: 2022-01-16T18:21:13.632Z State Change CONFLICT: informs
Error: Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed.
    at CDPSession.send (C:\Ocidental\Sistemas\Web\Auxiliares\wppconnect\wppconnect-server\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:214:35)
    at ExecutionContext._evaluateInternal (C:\Ocidental\Sistemas\Web\Auxiliares\wppconnect\wppconnect-server\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:204:50)
    at ExecutionContext.evaluate (C:\Ocidental\Sistemas\Web\Auxiliares\wppconnect\wppconnect-server\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:110:27)
    at DOMWorld.evaluate (C:\Ocidental\Sistemas\Web\Auxiliares\wppconnect\wppconnect-server\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:95:24)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by fabioselau077** [comment]
Same here

**Comment by renat473** [comment]
fix #474
