### ISSUE TITLE
não envia msg após att de 21/01/2022

### ISSUE THREAD

**Issue by nadomendes** [wppconnect-team/wppconnect-server#497]
após uma tentativa de envio de txt:
Error: "wap:queryDisappearingMode:unsupported"
    at /home/wppconnect-server/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/eval                              uate-and-return.js:103:33
    at step (/home/wppconnect-server/node_modules/@wppconnect-team/wppconnect/dist/api/helper                              s/evaluate-and-return.js:49:23)
    at Object.next (/home/wppconnect-server/node_modules/@wppconnect-team/wppconnect/dist/api                              /helpers/evaluate-and-return.js:30:53)
    at fulfilled (/home/wppconnect-server/node_modules/@wppconnect-team/wppconnect/dist/api/h                              elpers/evaluate-and-return.js:21:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  '0': 'w',
  '1': 'a',
  '2': 'p',
  '3': ':',
  '4': 'q',
  '5': 'u',
  '6': 'e',
  '7': 'r',
  '8': 'y',
  '9': 'D',
  '10': 'i',
  '11': 's',
  '12': 'a',
  '13': 'p',
  '14': 'p',
  '15': 'e',
  '16': 'a',
  '17': 'r',
  '18': 'i',
  '19': 'n',
  '20': 'g',
  '21': 'M',
  '22': 'o',
  '23': 'd',
  '24': 'e',
  '25': ':',
  '26': 'u',
  '27': 'n',
  '28': 's',
  '29': 'u',
  '30': 'p',
  '31': 'p',
  '32': 'o',
  '33': 'r',
  '34': 't',
  '35': 'e',
  '36': 'd'
}
error: 2022-01-21T17:03:02.290Z Cannot read properties of undefined (reading 'numberExists')                               - TypeError: Cannot read properties of undefined (reading 'numberExists')
    at statusConnection (/home/wppconnect-server/src/middleware/statusConnection.js:32:24)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by ghsgabriel** [comment]
@nadomendes  , Pode fornecer mais informações? Um exemplo de código? Como posso reproduzir

Por favor preencha o formulário:

    WPPConnect version(s): X.Y.Z
    WA-JS version(s): X.Y.Z
    Browser: Chrome XX / Chromium XX
    OS: Windows X / OSX X.Y.Z
    Node version: Node XY
    WhatsApp version: X.YYYY.ZZ
    MultiDevice (BETA): yes/no


Mas aproveitando, tenta apagar a node_modules, atualizar o server, instalar os pacotes novamente, buildar e ai iniciar o server.

**Comment by nadomendes** [comment]
WPPConnect version(s): 21/01/2022
WA-JS version(s): 1.1.9
Browser: Chrome XX / Chromium XX
OS: Ubuntu 20.04
Node version: Node 16
WhatsApp version: 2.2144.11
MultiDevice (BETA): no

o do browser não sei ver

**Comment by nadomendes** [comment]
fiz o que vc falou irmão, apaguei o node_modules e normalizou obrigado!
