### ISSUE TITLE
Error during sending message

### ISSUE THREAD

**Issue by JoyG42** [wppconnect-team/wppconnect-server#582]
## Description

After connecting when I send message this error occured

## Environment

- **Wppconnect-server version(s):** 1.1.21
- **Browser:** Chromium
- **OS:** Linux
- **Node version:** v17.4.0
- **WhatsApp version:** 2.2206.5
- **MultiDevice (BETA):** yes
- **config.json:** 
```JSON
{
  "secretKey": "4091603c7fb5f72a4bd1",
  "host": "http://localhost",
  "port": "21465",
  "deviceName" : "WppConnect",
  "startAllSession": true,
  "tokenStoreType": "file",
  "webhook": {
    "url": null,
    "autoDownload": true,
    "uploadS3": false,
    "readMessage": true,
    "allUnreadOnStart": false,
    "listenAcks": true,
    "onPresenceChanged": true,
    "onParticipantsChanged": true
  },
  "archive": {
    "enable": false,
    "waitTime": 10,
    "daysToArchive": 45
  },
  "log": {
    "level": "error",
    "logger": ["console", "file"]
  },
  "createOptions": {
    "whatsappVersion": null,
    "browserArgs": [
      "--disable-web-security",
      "--no-sandbox",
      "--disable-web-security",
      "--aggressive-cache-discard",
      "--disable-cache",
      "--disable-application-cache",
      "--disable-offline-load-stale-cache",
      "--disk-cache-size=0",
      "--disable-background-networking",
      "--disable-default-apps",
      "--disable-extensions",
      "--disable-sync",
      "--disable-translate",
      "--hide-scrollbars",
      "--metrics-recording-only",
      "--mute-audio",
      "--no-first-run",
      "--safebrowsing-disable-auto-update",
      "--ignore-certificate-errors",
      "--ignore-ssl-errors",
      "--ignore-certificate-errors-spki-list"
    ]
  },
  "mapper": {
    "enable": false,
    "prefix": "tagone-"
  },
  "db": {
    "mongodbDatabase": "tokens",
    "mongodbCollection": "",
    "mongodbUser": "",
    "mongodbPassword": "",
    "mongodbHost": "",
    "mongoIsRemote": true,
    "mongoURLRemote": "",
    "mongodbPort": 27017,
    "redisHost": "localhost",
    "redisPort": 6379,
    "redisPassword": "",
    "redisDb": 0,
    "redisPrefix": "docker"
  }
}

```

## Steps to Reproduce
1. Start node server
2. Start Session and Scan QR code
3. Send Message 

## Log Output

```
error: 2022-03-01T17:06:23.221Z "Module Constants not found with e=>0===e.default.ACK.CLOCK" - Error: "Module Constants not found with e=>0===e.default.ACK.CLOCK"
    at /data/wppconnect-Karmanye/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:103:33
    at step (/data/wppconnect-Karmanye/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:49:23)
    at Object.next (/data/wppconnect-Karmanye/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:30:53)
    at fulfilled (/data/wppconnect-Karmanye/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:21:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
error: 2022-03-01T17:09:16.543Z "Module Constants not found with e=>0===e.default.ACK.CLOCK" - Error: "Module Constants not found with e=>0===e.default.ACK.CLOCK"
    at /data/wppconnect-Karmanye/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:103:33
    at step (/data/wppconnect-Karmanye/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:49:23)
    at Object.next (/data/wppconnect-Karmanye/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:30:53)
    at fulfilled (/data/wppconnect-Karmanye/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:21:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

```

**Comment by JoyG42** [comment]
Please suggest if anything wrong, I'm using MultiDevice on Whatsapp (Not Business)

Working Functions:
- send-link-preview
- send-file

Not Working:
- send-message
- contact-vcard
