### ISSUE TITLE
Send-File-base64 error

### ISSUE THREAD

**Issue by shoerofi** [wppconnect-team/wppconnect-server#781]
## Description

error when trying to send-file-base64

## Environment

- **Wppconnect-server version(s):** [1.3.3]
- **Browser:** [Google Chrome]
- **OS:** [M1 macbook air, macOS Monterey]
- **Node version:** [16.15.0]
- **WhatsApp version:** [2.2220.8]
- **MultiDevice (BETA):** yes
- **config.json:** 

```
{
  "secretKey": "THISISMYSECURETOKEN",
  "host": "http://localhost",
  "port": "21465",
  "customUserDataDir": "./userDataDir/",
  "deviceName": "WppConnect",
  "startAllSession": true,
  "tokenStoreType": "file",
  "maxListeners": 15,
  "webhook": {
    "url": null,
    "autoDownload": true,
    "uploadS3": false,
    "readMessage": true,
    "allUnreadOnStart": false,
    "listenAcks": true,
    "onPresenceChanged": true,
    "onParticipantsChanged": true
  },
  "archive": {
    "enable": false,
    "waitTime": 10,
    "daysToArchive": 45
  },
  "log": {
    "level": "error",
    "logger": ["console", "file"]
  },
  "createOptions": {
    "whatsappVersion": null,
    "browserArgs": [
      "--disable-web-security",
      "--no-sandbox",
      "--disable-web-security",
      "--aggressive-cache-discard",
      "--disable-cache",
      "--disable-application-cache",
      "--disable-offline-load-stale-cache",
      "--disk-cache-size=0",
      "--disable-background-networking",
      "--disable-default-apps",
      "--disable-extensions",
      "--disable-sync",
      "--disable-translate",
      "--hide-scrollbars",
      "--metrics-recording-only",
      "--mute-audio",
      "--no-first-run",
      "--safebrowsing-disable-auto-update",
      "--ignore-certificate-errors",
      "--ignore-ssl-errors",
      "--ignore-certificate-errors-spki-list"
    ]
  },
  "mapper": {
    "enable": false,
    "prefix": "tagone-"
  },
  "db": {
    "mongodbDatabase": "tokens",
    "mongodbCollection": "",
    "mongodbUser": "",
    "mongodbPassword": "",
    "mongodbHost": "",
    "mongoIsRemote": true,
    "mongoURLRemote": "",
    "mongodbPort": 27017,
    "redisHost": "localhost",
    "redisPort": 6379,
    "redisPassword": "",
    "redisDb": 0,
    "redisPrefix": "docker"
  }
}
```

## Steps to Reproduce

just trying to send-file-base64 from postman with WPPConnect API REST

## Log Output

```
0|npm    | error: 2022-06-08T12:33:44.366Z Cannot read properties of undefined (reading '0') - Error: Cannot read properties of undefined (reading '0')
0|npm    |     at /Users/shoerofi/Projects/getnotif/getnotif-engine/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:106:31
0|npm    |     at step (/Users/shoerofi/Projects/getnotif/getnotif-engine/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:49:23)
0|npm    |     at Object.next (/Users/shoerofi/Projects/getnotif/getnotif-engine/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:30:53)
0|npm    |     at fulfilled (/Users/shoerofi/Projects/getnotif/getnotif-engine/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:21:58)
0|npm    |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
0|npm    | JS Stack: TypeError: Cannot read properties of undefined (reading '0')
0|npm    |     at Object.<anonymous> (/Users/shoerofi/Projects/getnotif/getnotif-engine/node_modules/@wppconnect-team/wppconnect/dist/lib/wapi/wapi.js:1:31009)
0|npm    |     at Generator.next (<anonymous>)
0|npm    |     at ye (/Users/shoerofi/Projects/getnotif/getnotif-engine/node_modules/@wppconnect-team/wppconnect/dist/lib/wapi/wapi.js:1:30092)
0|npm    |     at a (/Users/shoerofi/Projects/getnotif/getnotif-engine/node_modules/@wppconnect-team/wppconnect/dist/lib/wapi/wapi.js:1:30296)
0|npm    |     at W (https://web.whatsapp.com/bootstrap_qr.a817218351c7d3e5be74.js:32:83013)
0|npm    |     at MutationObserver.x (https://web.whatsapp.com/bootstrap_qr.a817218351c7d3e5be74.js:32:79590)
```

## Your Code

```
no code modified
```

## Additional context / Screenshot

-

**Comment by shoerofi** [comment]
Updated to the latest wppconnect 1.14.0 fix the issue. Thanks
