### ISSUE TITLE
ArchiveChat malforming chatid

### ISSUE THREAD

**Issue by Sau64** [wppconnect-team/wppconnect-server#785]
## Description

ArchiveChat is not working properly. Not from code nor swagger.

i send phone like this: **5491112345678**
wppconnect-server tries to call it like this **5491112345678@c.us@c.us** [see log error]

somewhere it is adding twice the **@c.us**

## Environment

- **Wppconnect-server version(s):** 1.3.3
- **Node version:** 16
- **WhatsApp version:** 2.2220.8
- **MultiDevice (BETA):** yes

## Log Output

error: 2022-06-10T21:46:19.403Z Invalid WID value for 5491112345678@c.us@c.us - Error: Invalid WID value for 5491112345678@c.us@c.us
    at /var/www/htdocs/whatsapp/wppconnect-server-main/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:106:31
    at step (/var/www/htdocs/whatsapp/wppconnect-server-main/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:49:23)
    at Object.next (/var/www/htdocs/whatsapp/wppconnect-server-main/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:30:53)
    at fulfilled (/var/www/htdocs/whatsapp/wppconnect-server-main/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:21:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
JS Stack: Error: Invalid WID value for 5491112345678@c.us@c.us
    at t.assertWid (/var/www/htdocs/whatsapp/wppconnect-server-main/node_modules/@wppconnect/wa-js/dist/wppconnect-wa.js:2:88309)
    at Object.s (/var/www/htdocs/whatsapp/wppconnect-server-main/node_modules/@wppconnect/wa-js/dist/wppconnect-wa.js:2:102688)
    at __puppeteer_evaluation_script__:58:41
    at __puppeteer_evaluation_script__:59:24
    at Y (https://web.whatsapp.com/bootstrap_qr.a817218351c7d3e5be74.js:32:82865)
    at new y (https://web.whatsapp.com/bootstrap_qr.a817218351c7d3e5be74.js:32:75432)
    at anonymous (__puppeteer_evaluation_script__:54:14)

**Comment by icleitoncosta** [comment]
Close by commit c3f6420f8129dd4069d2ba05aa911a352914afb4
