### ISSUE TITLE
Logout From Mobile 

### ISSUE THREAD

**Issue by Akash-Rathore** [wppconnect-team/wppconnect-server#850]
error:    Unhandled Rejection: ProtocolError: Protocol error (Runtime.callFunctionOn): Target closed.
    at C:\Users\Administrator\Desktop\messagerider2.o\web_whatsweb\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:230:24
    at new Promise (<anonymous>)
    at CDPSession.send (C:\Users\Administrator\Desktop\messagerider2.o\web_whatsweb\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:226:16)
    at ExecutionContext._evaluateInternal (C:\Users\Administrator\Desktop\messagerider2.o\web_whatsweb\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:204:50)
    at ExecutionContext.evaluate (C:\Users\Administrator\Desktop\messagerider2.o\web_whatsweb\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:110:27)
    at DOMWorld.evaluate (C:\Users\Administrat

**Comment by icleitoncosta** [comment]
Hello @Akash-Rathore, please:
## Description

[Description of the bug, When Issue Happens]

## Environment

- **Wppconnect-server version(s):** [e.g. 2.0.27, 2.2.1]
- **Browser:** [e.g. Chrome 87, Chromium 85]
- **Node version:** [e.g. Node 8, Node 14]
- **MultiDevice (BETA):** yes/no

## Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

## Log Output

```
If relevant, paste all of your Log Output
```

## Additional context / Screenshot

Add any other context about the problem here. If applicable, add screenshots to help explain.
