### ISSUE TITLE
ContactBlocked: Contact is blocked

### ISSUE THREAD

**Issue by dcrec1** [wppconnect-team/wppconnect-server#900]
## Description

When trying to start a closed session, the error happens.

## Environment

- **Wppconnect-server version(s):** 11880fd677d6df2e584ddfbc35c6a189cae636fd
- **OS:** Ubuntu 20.04.4 LTS
- **Node version:** v16.15.1

## Steps to Reproduce

1. Call `start-session` with a webhook URL.

## Log Output

```
1|server  | error: 2022-09-17T14:11:47.079Z Contact is blocked - ContactBlocked: Contact is blocked
1|server  |     at /var/local/apps/wppconnect-server/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:106:31
1|server  |     at step (/var/local/apps/wppconnect-server/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:49:23)
1|server  |     at Object.next (/var/local/apps/wppconnect-server/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:30:53)
1|server  |     at fulfilled (/var/local/apps/wppconnect-server/node_modules/@wppconnect-team/wppconnect/dist/api/helpers/evaluate-and-return.js:21:58)
1|server  |     at runMicrotasks (<anonymous>)
1|server  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
1|server  | JS Stack: ContactBlocked: Contact is blocked
1|server  |     at new i (https://web.whatsapp.com/bootstrap_qr.a817218351c7d3e5be74.js:32:151305)
1|server  |     at new i (https://web.whatsapp.com/bootstrap_qr.a817218351c7d3e5be74.js:33:17281)
1|server  |     at https://web.whatsapp.com/bootstrap_qr.a817218351c7d3e5be74.js:33:107069
1|server  |     at t.promiseCallSync (https://web.whatsapp.com/bootstrap_qr.a817218351c7d3e5be74.js:32:67563)
1|server  |     at t.sendMsgRecord (https://web.whatsapp.com/bootstrap_qr.a817218351c7d3e5be74.js:33:106630)
1|server  |     at https://web.whatsapp.com/bootstrap_qr.a817218351c7d3e5be74.js:32:265183
1|server  |     at Generator.next (<anonymous>)
1|server  |     at t (https://web.whatsapp.com/vendor1~bootstrap_qr.d22113b351145f031a1c.js:2:65356)
1|server  |     at s (https://web.whatsapp.com/vendor1~bootstrap_qr.d22113b351145f031a1c.js:2:65567)
1|server  |     at W (https://web.whatsapp.com/bootstrap_qr.a817218351c7d3e5be74.js:32:83013)
```

**Comment by icleitoncosta** [comment]
Could you put here the step by step to reproduce the error?

**Comment by dcrec1** [comment]
It's in the first post, I'm just posting `start-session`.
