### ISSUE TITLE
AUTO RECOVER FROM SESSION CLOSE

### ISSUE THREAD

**Issue by leohturbo** [wppconnect-team/wppconnect-server#909]
error: 2022-09-22T01:02:48.051Z Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed. - Error: Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed.
    at CDPSession.send (C:\Users\Admin\Documents\whatsking\king\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:265:35)
    at ExecutionContext._ExecutionContext_evaluate (C:\Users\Admin\Documents\whatsking\king\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:268:46)

Create a way to auto recover from sessions that is self closed by WhatsApp without reasons.
Maybe restart the browser of puppeter.

PTBR:
Criar um meio de auto recuperar sessões que são fechadas pelo próprio WhatsApp sem motivos.
Talvez reiniciar o navegador do puppeter.

**Comment by adrianokelvio** [comment]
Estou com mesmo bug

**Comment by icleitoncosta** [comment]
This has been fixed in version 1.6.4
