### ISSUE TITLE
400 - Bad request returned by send-message

### ISSUE THREAD

**Issue by Rcpitalia** [wppconnect-team/wppconnect-server#998]
**Before adding this issue, make sure you do the following to make sure this is not a duplicate:**

1. Search through the repo's previous issues
2. Read through the readme at least once
3. Search the docs for the feature you're looking for

We primarily use GitHub as an issue tracker; for usage and support questions, please check out these resources below. Thanks! 😁.

---

- Discord: https://discord.gg/qCJ95FVbzR
- WhatsApp Group: [https://chat.whatsapp.com/EGLVbeFGgt40OkbOCX8Sei]
- Also have a look at the readme for more information on how to get support:

**Comment by Rcpitalia** [comment]
Hi, 
i use WPPCONNECT-Server Ver. 1.7.1
Sending the same text message to different numbers, the 
http://localhost:21465/api/{session}/send-message
returns 
400 - Bad request only for some phone numbers.
If I send the same text from WA on the phone it works.

**Comment by icleitoncosta** [comment]
Can you put here the code you use to run the function?

> Hi, i use WPPCONNECT-Server Ver. 1.7.1 Sending the same text message to different numbers, the [http://localhost:21465/api/{session}/send-message](http://localhost:21465/api/%7Bsession%7D/send-message) returns 400 - Bad request only for some phone numbers. If I send the same text from WA on the phone it works.

**Comment by Rcpitalia** [comment]
Wppconnect-server 1.7.1 Windows 10
curl --location --request POST 'http://192.168.1.16:21465/api/acquamanager/send-message' \
--header 'Content-Type: application/json; charset=utf-8' \
--header 'Accept: application/json' \
--header 'Authorization: Bearer $2b$10$MhuRQKNLDl13s3NmnLFsWeonlolVV8t.__giHpMUHYEKJb.uNh4Wy' \
--data-raw '{
          "phone": "3924852675",
          "message": "Ciao"
        }'

this is the response:	
Error code 400 Bad Request	
{"response":null,"status":"Connected","message":"O número 3924852675 não existe."}

No problem if I send the same message from wa on phone or WaWeb.
I try also adding international prefix +39 to the number

**Comment by Rcpitalia** [comment]
This is the trace. I try with and without the international prefix 0039.
the version of wppconnect-server is 1.8
info: 2022-12-16T20:05:28.705Z Started Session: acquamanager
Error: wid error: invalid wid: 00393924852675@c.us
    at C:\webapp\wppconnect-server_WS\wppconnect-server-main\node_modules\@wppconnect-team\wppconnect\dist\api\helpers\evaluate-and-return.js:107:31
    at step (C:\webapp\wppconnect-server_WS\wppconnect-server-main\node_modules\@wppconnect-team\wppconnect\dist\api\helpers\evaluate-and-return.js:49:23)
    at Object.next (C:\webapp\wppconnect-server_WS\wppconnect-server-main\node_modules\@wppconnect-team\wppconnect\dist\api\helpers\evaluate-and-return.js:30:53)
    at fulfilled (C:\webapp\wppconnect-server_WS\wppconnect-server-main\node_modules\@wppconnect-team\wppconnect\dist\api\helpers\evaluate-and-return.js:21:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
JS Stack: Error: wid error: invalid wid: 00393924852675@c.us
    at new u (https://web.whatsapp.com/bootstrap_qr.c8a228a8ac9e7fc0fc33.js:71:44905)
    at Object.s [as createWid] (https://web.whatsapp.com/bootstrap_qr.c8a228a8ac9e7fc0fc33.js:71:49510)
    at t.createWid (C:\webapp\wppconnect-server_WS\wppconnect-server-main\node_modules\@wppconnect\wa-js\dist\wppconnect-wa.js:2:242052)
    at t.assertWid (C:\webapp\wppconnect-server_WS\wppconnect-server-main\node_modules\@wppconnect\wa-js\dist\wppconnect-wa.js:2:98081)
    at t.queryExists (C:\webapp\wppconnect-server_WS\wppconnect-server-main\node_modules\@wppconnect\wa-js\dist\wppconnect-wa.js:2:188555)
    at Object.<anonymous> (C:\webapp\wppconnect-server_WS\wppconnect-server-main\node_modules\@wppconnect-team\wppconnect\dist\lib\wapi\wapi.js:1:78112)
    at Generator.next (<anonymous>)
    at yn (C:\webapp\wppconnect-server_WS\wppconnect-server-main\node_modules\@wppconnect-team\wppconnect\dist\lib\wapi\wapi.js:1:61869)
    at a (C:\webapp\wppconnect-server_WS\wppconnect-server-main\node_modules\@wppconnect-team\wppconnect\dist\lib\wapi\wapi.js:1:62073)
    at C:\webapp\wppconnect-server_WS\wppconnect-server-main\node_modules\@wppconnect-team\wppconnect\dist\lib\wapi\wapi.js:1:62134

**Comment by icleitoncosta** [comment]
Hello, i'm testing this issue on my wpp.

Please, update your wppconnect version: `yarn install wppconnect/wppconnect@latest`
Update your wppconnect-server version (clone github)

Send the message like:

```
{
  "phone": "393924852675",
  "message": "Hello World",
  "isGroup": false
}
```
